### ISSUE TITLE
 doing 0 damage with Grenade Launcher

### ISSUE THREAD

**Issue by exzoyoloatwrk** [Ch1ckenscoop/svn-rd#1]
ok so i have been testing and found that Vegas , faith , wildcat, wolfe are doing 0 damage with Grenade Launcher. I will try to fix this if i found how

**Comment by exzoyoloatwrk** [comment]
cfg error or something SOLVED

**Comment by Softcopy** [comment]
After traced, it was caused by ASRD "asw_skill_grenades_cluster_dmg_base" cvar default to "0", the original default value should be "80". If you didn't enable this entity in customsetttings.cfg on Ch1ckensCoop after fresh installation, Vegas/Faith/Wildcat/Wolfe would get "0" damage from grenade launcher.

Thanks for the information, Ch1ckensCoop also has corrected the default cvar to "80", so that no zero damage from grenade launcher would be happened
